# -*- coding: utf-8 -*-
"""Amazon_product_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-KXLzda48dn99wT-HOrlP7k361TJ482
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,r2_score

df = pd.read_csv('/content/amazon_product.csv')

df.shape

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.tail()

import nltk

df.drop('id',axis=1)

from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")

def tokenize_stem(text):
    tokens = nltk.word_tokenize(text.lower())
    stem = [stemmer.stem(w) for w in tokens]
    return " ".join(stem)

